### ISSUE TITLE
Release testing versions for Android on Github

### ISSUE THREAD

**Issue by Humorist2601** [Beaver-Notes/Beaver-pocket#1]
**Question or Assistance Request**

- [x] I have reviewed existing issues and discussions to find a solution to my question.
- [x] I have checked the documentation and relevant resources for answers.
- [x] This question is related to the project and within the scope of this repository.

**Description**
Hello

Love your app on Linux and got to know about the mobile version. Unfortunately I don't have an iPhone so can you kindly release Android releases. I can help in testing the app and raising issues over here.

**Environment (if applicable)**
- Operating System: Android
- Operating System Version: 14
- Version of the project : -

**Comment by Daniele-rolli** [comment]
Hey, thanks for the feedback. I've released an APK on GitHub for version 1.1.1; however, it doesn't work properly due to some Android-specific issues that are being addressed. Thanks for your patience. I hope you'll soon be able to enjoy Beaver Notes on Android.
