### ISSUE TITLE
Note's title is barely visible; it cannot be edited

### ISSUE THREAD

**Issue by danielbmeireles** [Beaver-Notes/Beaver-pocket#18]
**Describe the bug**
Note's title is barely visible; it cannot be edited.

**To Reproduce**
1. Click on the "+" icon
2. A new note will be created, but the title will be covered by the top bar containing the focus mode and the search icon

**Expected behavior**
The user should be able to read and edit the note's title.

**Screenshots**
![5028683130931883626](https://github.com/user-attachments/assets/f6961fc1-d7f7-4a97-b3c5-51b6d208dc97)

**Smartphone (please complete the following information):**
 - Device: Pixel 8a
 - OS: Android 15 (Security Update - Nov 5, 2024)
 - OS Build: AP34.241105.007
 - Browser: Firefox
 - Version: 132.0.2

**Comment by Daniele-rolli** [comment]
Thank you for your feedback! We’re currently working on a new release candidate that addresses this issue. We appreciate your patience and support as we work on the last touches. You can check our progress at #17.
