### ISSUE TITLE
Can't create file in Android 10+

### ISSUE THREAD

**Issue by bigshans** [Beaver-Notes/Beaver-pocket#8]
**Describe the bug**
Pocket can't create files on Android 10.

**Screenshots**
![图片](https://github.com/Daniele-rolli/Beaver-pocket/assets/26884666/1162ecc6-ffc4-40b9-ba82-4af16f5548ab)

**Smartphone (please complete the following information):**
 - OS: Android 13, Android 14

**Additional context**
1. https://stackoverflow.com/a/68749082
2. https://github.com/ionic-team/capacitor/issues/2916

**Comment by Daniele-rolli** [comment]
Thanks for pointing this out. I've looked into the issue and the additional context you provided, and I've updated the AndroidManifest.xml accordingly. The only issue we have is the following: The Google Play store has a policy that limits the usage of MANAGE_EXTERNAL_STORAGE, but we'll deal with Google later if need be.

**Comment by Daniele-rolli** [comment]
So, let me get this straight: it does work now, but it doesn't ask for permission before accessing the device's filesystem, right?"

**Comment by Daniele-rolli** [comment]
Uhm, I'll look into it, however it does work on android studio somehow.

**Comment by bigshans** [comment]
> Uhm, I'll look into it, however it does work on android studio somehow.

What's your Android version?

**Comment by Daniele-rolli** [comment]
Here's the emulator's about section, as you can see it's running android 13 so it should be part of this issue. Anyway I believe I've found something in [capacitor's documentation](https://capacitorjs.com/docs/apis/filesystem#checkpermissions) concerning permissions.

 ![Screenshot_20240311_163325](https://github.com/Daniele-rolli/Beaver-pocket/assets/67503004/19bcd3ac-a031-4fe8-bd84-f4581707507f)

**Comment by Daniele-rolli** [comment]
I've browsed a bit and maybe the only quick fix is changing the way we store files. Since the app doesn't have access to the Documents folder anymore, we can change it to save the data under Data.
